"""Provide constants used in the elfinder api."""
# API requests constants
API_CURRENT = "current"
API_TARGET = "target"
API_CMD = "cmd"
API_UPLOAD = "upload[]"
API_TARGETS = "targets[]"
API_TREE = "tree"
API_NAME = "name"
API_CONTENT = "content"
API_SRC = "src"
API_DST = "dst"
API_CUT = "cut"
API_INIT = "init"
API_TYPE = "type"
API_WIDTH = "width"
API_HEIGHT = "height"
API_Q = "q"

# Archive constants
ARCHIVE_CMD = "cmd"
ARCHIVE_ARGC = "argc"
ARCHIVE_EXT = "ext"

# Info constants
INFO_NAME = "name"
INFO_HASH = "hash"
INFO_MIME = "mime"
INFO_READ = "read"
INFO_WRITE = "write"
INFO_LOCKED = "locked"
INFO_TS = "ts"
INFO_VOLUMEID = "volumeid"
INFO_DIRS = "dirs"
INFO_PHASH = "phash"
INFO_LINK = "link"
INFO_ALIAS = "alias"
INFO_SIZE = "size"
INFO_URL = "url"
INFO_DIM = "dim"
INFO_RESIZE = "resize"
INFO_TMB = "tmb"

# Response constants
R_ADDED = "added"
R_API = "api"
R_CWD = "cwd"
R_DEBUG = "debug"
R_DIM = "dim"
R_ERROR = "error"
R_FILE = "file"  # This is not part of api 2.1
R_HASHES = "hashes"
R_IMAGES = "images"
R_NETDRIVERS = "netDrivers"
R_OPTIONS = "options"
R_REMOVED = "removed"
R_TMB = "tmb"  # This is not part of api 2.1
R_UPLMAXFILE = "uplMaxFile"
R_UPLMAXSIZE = "uplMaxSize"
R_WARNING = "warning"
