name: Draft release

on:
  workflow_dispatch:

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
